- name: Install pip
  apt:
    name: python-pip
    update_cache: yes
  register: result
  retries: 5
  delay: 60
  until: result|succeeded
  when: ansible_os_family == "Debian"

- block:
    - name: Install epel 
      yum:
        name: epel-release
        update_cache: yes

    - name: Install pip
      yum:
        name: python-pip
      register: result
      retries: 5
      delay: 60
      until: result|succeeded
  when: ansible_os_family == "RedHat"
