- name: Start zuul console daemon
  zuul_console:

- name: Create inventory for network node
  copy:
    content: |
      [{{ platform }}]
      {{ hostvars[platform]['ansible_host'] }} ansible_connection=local
    dest: /tmp/inventory

- shell: cat /tmp/inventory

- shell: "pip install -r requirements.txt && source hacking/env-setup && ansible-test network-integration {{ platform }} --inventory /tmp/inventory -vvv"
  args:
    executable: /bin/bash
    chdir: "{{ zuul.project.src_dir }}"
