- name: Start zuul console daemon
  zuul_console:

- name: Create inventory for network node
  copy:
    content: |
      [{{ platform }}]
      {{ hostvars[platform]['ansible_host'] }} ansible_connection=local ansible_network_os={{ platform }} ansible_ssh_private_key_file=/home/zuul/.ssh/id_rsa
    dest: /tmp/inventory

- include_role:
    name: install-pip
  become: yes

- include_role:
    name: install-pip-requirements
  become: yes

- name: Install packages needed for network integration tests
  pip:
    name: pexpect
  become: yes

- shell: "source hacking/env-setup && ansible-test network-integration {{ platform }}{{ tests_regex }} --inventory /tmp/inventory -vvv"
  args:
    executable: /bin/bash
    chdir: "{{ zuul.project.src_dir }}"
