- name: Start zuul console daemon
  zuul_console:

- name: Create inventory folder
  file:
    path: /tmp/inventory
    state: directory

- name: Create inventory group_vars folder
  file:
    path: /tmp/inventory/group_vars
    state: directory

- name: Create hosts inventory file
  template:
    src: hosts.j2
    dest: /tmp/inventory/hosts

- name: Create platform group_vars file
  template:
    src: group_vars.j2
    dest: /tmp/inventory/group_vars/{{ net_platform }}

- include_role:
    name: install-pip
  become: yes

- include_role:
    name: install-pip-requirements
  become: yes

- name: Install packages needed for network integration tests
  pip:
    name: pexpect
  become: yes

- shell: "source hacking/env-setup && ansible-test network-integration {{ net_platform }}{{ net_target_regex }} --inventory /tmp/inventory -vvv"
  args:
    executable: /bin/bash
    chdir: "{{ zuul.project.src_dir }}"
