- name: Start zuul console daemon
  zuul_console:

- name: Create inventory for network node
  copy:
    content: |
      [{{ platform }}]
      {{ hostvars[platform]['ansible_host'] }} ansible_connection=local ansible_network_os={{ platform }} ansible_ssh_private_key_file=/home/zuul/.ssh/id_rsa
    dest: /tmp/inventory

- shell: "apt-get -y update && apt-get -y install python-pip && pip install -r requirements.txt"
  args:
    executable: /bin/bash
    chdir: "{{ zuul.project.src_dir }}"
  become: yes

- shell: "pip install pexpect"
  args:
    executable: /bin/bash
  become: yes

- shell: "source hacking/env-setup && ansible-test network-integration {{ platform }}{{ tests_regex }} --inventory /tmp/inventory -vvv"
  args:
    executable: /bin/bash
    chdir: "{{ zuul.project.src_dir }}"
